### ISSUE TITLE
TRUE and FALSE undefined with Arduino boards, IDE version 1.8.3+ (with workaround)

### ISSUE THREAD

**Issue by alicemirror** [Infineon/DC-Motor-Control-TLE94112EL#1]
The library works perfectly with the Infineon board **XMC1100** Arduino compatible. Installing the shield on an **Arduino UNO** instead compilation can't happen. Investigating in the errors list I found the following messages:

```
C:\Users\enrico\Desktop\Arduino\libraries\TLE94112\src\TLE94112.cpp:42:13: error: 'FALSE' was not declared in this scope
  mEnabled = FALSE;

C:\Users\enrico\Desktop\Arduino\libraries\TLE94112\src\TLE94112.cpp:50:13: error: 'TRUE' was not declared in this scope
  mEnabled = TRUE;

C:\Users\enrico\Desktop\Arduino\libraries\TLE94112\src\TLE94112.cpp:64:13: error: 'FALSE' was not declared in this scope
  mEnabled = FALSE;

[etc...]
```

I have added a couple of conditions defines in the library header file as shown below

```
#ifndef TLE94112_CONF_H
#define TLE94112_CONF_H

// PATCH START ===================================================
/*
	The following two conditional define patches the compatibility of the library
	with NON-Infineon boards. The boolean TRUE and FALSE (uppercase) are defined
	in the Arduino IDE Infineon XMC110 library but are note recognised when
	the board is set to Arduino UNO/Genuino. It is reasonable suppose that this
	same issue - untested - exhists too with the other boards of the Arduino
	family supported by the Arduino IDE versione 1.8.3 and further
	
	Enrico Miglino <balearicdynamics@gmail.com>
	July, 5, 2017
*/
#ifndef TRUE
#define TRUE true
#endif

#ifndef FALSE
#define FALSE false
#endif
// ================================================= PATCH END

#include "Arduino.h"
```

This patch has been added in the header file **Arduino/libraries/TLE94112/util/tle94112_conf.h**

**Comment by alicemirror** [comment]
**Update**

After setting the workaround as described in the above issue, I moved again to work with the XMC110 and got the same opposite problem. So I updated the workaround including it in a conditional preprocessor s shown below:

```
#ifdef _INFINEON_BOARD
#ifndef TRUE
#define TRUE true
#endif

#ifndef FALSE
#define FALSE false
#endif
#endif
#include "Arduino.h"
```

Then before including the library in your sketch it is needed to define or undefine the `_INFINEON_BOARD` global as shown in the example below

```
#define _INFINEON_BOARD // "#undef" if not using Infineon XMC1100 Boot Arduino compatible board
#include <TLE94112.h>

```

**Comment by mhollfelder** [comment]
This bug should now be resolved with the new [release](https://github.com/Infineon/DC-Motor-Control-TLE94112EL/releases/tag/V1.0.1).

We resolved it using preprocessor directives as also done by you :)

Best regards,

Manuel

**Comment by alicemirror** [comment]
Grreat Job.

Cheers, Enrico
